### ISSUE TITLE
when compiling buzzer.c - can't find the libopencm3_stm32f1.ld: No such file or directory

### ISSUE THREAD

**Issue by n01287334** [themightyteam/bluepill-examples#1]
![questioncompile](https://user-images.githubusercontent.com/71231869/100385476-b3cac900-2ff0-11eb-9ec5-1dd514bf40ee.png)

**Comment by n01287334** [comment]
Please help.

**Comment by eLeDe** [comment]
Hello @n01287334, please, try using an earlier version of arm-none-eabi (6 or 7).

Alternatively you can use the Makefile from the root of the project that builds a Docker image with the correct toolchain. With that Makefile you only have to type `make examples/buzzer` to compile the buzzer example.
